export const CITIES = [
  "Ahmedabad",
  "Aligarh",
  "Amravati",
  "Amritsar",
  "Aurangabad",
  "Bengaluru",
  "Bhubaneswar",
  "Bhopal",
  "Chandigarh",
  "Chennai",
  "Coimbatore",
  "Dehradun",
  "Delhi",
  "Dhanbad",
  "Faridabad",
  "Guwahati",
  "Gwalior",
  "Indore",
  "Jabalpur",
  "Jaipur",
  "Jamshedpur",
  "Jodhpur",
  "Kanpur",
  "Kalyan‑Dombivali",
  "Kochi",
  "Kolhapur",
  "Kolkata",
  "Kota",
  "Ludhiana",
  "Lucknow",
  "Madurai",
  "Mangalore",
  "Meerut",
  "Mysore",
  "Nagpur",
  "Nanded",
  "Nashik",
  "Panipat",
  "Patna",
  "Pune",
  "Prayagraj",
  "Rajkot",
  "Ranchi",
  "Salem",
  "Surat",
  "Thiruvananthapuram",
  "Tiruchirappalli",
  "Vadodara",
  "Vasai‑Virar",
  "Vijayawada",
  "Visakhapatnam",
];

export const HeaderItems = [
  { href: "/", name: "Home"},
  { href: "/state", name: "State"},
  { href: "/country", name: "Country"},
  { href: "/cricket", name: "Cricket"},
  { href: "/cricket/live-scores", name: "Live Scores"},
  { href: "/entertainment", name: "Entertainment"},
  { href: "/business", name: "Business"},
  { href: "/career", name: "Career"},
  { href: "/foreign", name: "Foreign"},
  { href: "/astrology", name: "Religion"},
  { href: "/horoscope", name: "Horoscope"},
  { href: "/lifestyle", name: "Lifestyle"},
  { href: "/auto", name: "Auto"},
  { href: "/gadgets", name: "Gadgets"},
]